def Mudar2Ac(self):        
    self.Acre.setStyleSheet("QPushButton {\n"
    "    color: #333;\n"
    "    border: 2px solid #555;\n"
    "    border-radius: 15px;\n"
    "    border-style: outset;\n"
    "    background: qradialgradient(\n"
    "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
    "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
    "        );\n"
    "    padding: 5px;\n"
    "    }\n"
    "\n"
    "QPushButton:hover {\n"
    "    background: qradialgradient(\n"
    "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
    "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
    "        );\n"
    "    }\n"
    "\n"
    "QPushButton:pressed {\n"
    "    border-style: inset;\n"
    "    background: qradialgradient(\n"
    "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
    "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
    "        );\n"
    "    }")


def Mudar2Al(self):        
    self.Alagoas.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ap(self):
    self.Amapa.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Am(self):
    self.Amazonas.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ba(self):                    
    self.Bahia.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ce(self):                    
    self.Ceara.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Es(self):
    self.EspiritoSanto.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Go(self):                    
    self.Goias.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ma(self):                    
    self.Maranhao.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Mt(self):                    
    self.MatoGrosso.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ms(self):                    
    self.MatoGrossodoSul.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Mg(self):                    
    self.MinasGerais.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Pa(self):                   
    self.Para.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Pb(self):                    
    self.Paraiba.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Pr(self):                    
    self.Parana.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Pe(self):                    
    self.Pernambuco.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Pi(self):                    
    self.Piaui.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Rj(self):                    
    self.RiodeJaneiro.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Rn(self):                    
    self.RioGrandedoNorte.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Rs(self):                  
    self.RioGrandedoSul.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Ro(self):                    
    self.Rondonia.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Rr(self):                   
    self.Roraima.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Sc(self):                    
    self.SantaCatarina.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Sp(self):                    
    self.SaoPaulo.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2Se(self):                    
    self.Sergipe.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")

def Mudar2To(self):                    
    self.Tocantins.setStyleSheet("QPushButton {\n"
            "    color: #333;\n"
            "    border: 2px solid #555;\n"
            "    border-radius: 15px;\n"
            "    border-style: outset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    padding: 5px;\n"
            "    }\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 yellow, stop: 1 yellow\n"
            "        );\n"
            "    }")
